version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_app_production
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  web:
    build: .
    command: rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/budget_app_production
    volumes:
      - .:/app
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
