apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: budget-app-run
  namespace: default
spec:
  pipelineRef:
    name: budget-app-pipeline
  params:
    - name: git-url
      value: https://github.com/evans22j/Budget-App.git
    - name: image-url
      value: docker.io/vanuj447/budget-app:latest
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: budget-app-workspace-pvc

