apiVersion: v1
kind: Service
metadata:
  name: rails-service
  namespace: budget-app
spec:
  selector:
    app: budget-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31000
